### ISSUE TITLE
authentication check fails

### ISSUE THREAD

**Issue by normkatz** [InfyOmLabs/bootstrap-generator#1]
Reposted from an email I sent you.
I installed your laravel generator app and got it working for all crud tasks on a test table called questions.  But then I logged out of the web app by clicking logout on my /questions page in the header.  It took me to the login page.  Then I changed my browser URL to point back to /questions and I was able to view and edit my records.  Your app does not seem to be handling authentication at all except on the login page.  Can you tell me if that's a bug that you can reproduce and would be willing to fix?

Thanks!

**Comment by normkatz** [comment]
I solved the issue myself by surrounding the route::resource your generator creates in routes.php with a route::group as in:

Route::group(['middleware' => 'auth'], function () {
    Route::resource('questions', 'questionController');
});
Worked like a charm, except if I click the back button after logout, it takes me to the last view of the page I should no longer be able to see.  Probably needs a no-cache directive in the header.

**Comment by mitulgolakiya** [comment]
@normkatz great.
